### ISSUE TITLE
Week 1: Create your slack account

### ISSUE THREAD

**Issue by shamza0** [CubeStatistica/Professional-Training-for-Data-Science-C1#85]
- [ ] @shamza0 
- [ ]  @Mojoo-Star 
- [ ]  @Abdullahsulehri10 
- [ ]  @Jaybo44 
- [x] @Maryam-22844

**Comment by shamza0** [comment]
- [ ] @shamza0 
- [ ]

**Comment by Jaybo44** [comment]
- [ ] @shamza0 
- [ ]  @Mojoo-Star 
- [ ]  @Abdullahsulehri10 
- [ ]  @Jaybo44 
- [ ] @Maryam-22844
